<a href="https://colab.research.google.com/github/saurav11sarkar/Python/blob/main/session_18_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
pd.options.display.max_columns = None
# to show all the records, use the below code
# pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [2]:
# To get the details about the dataset, please visit
# https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
df = pd.read_csv(url)
df.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0

In [3]:
df.describe()

,Sl. No,Match No.,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,64.500000,32.500000,1.343750,43.476562,1.203125,0.117188,0.914062,11.257812,4.007812,4.835938,6.914062,4.343750,13.562500,4.671875,4.906250,4.648438,12.234375,92.703125,12.453125,169.281250,109.476562,14.812500,8.265625,1.726562,0.023438,12.320312,1.976562,502.859375,430.929688,19.523438,4.898438,4.468750,14.250000,0.335938,1.429688
std,37.094474,18.545539,1.342448,11.442403,1.324270,0.322907,1.150333,5.406683,2.588576,2.610630,3.998085,2.733397,6.901729,2.886595,3.080131,2.936573,6.176517,29.440547,18.152399,34.120661,30.776298,7.230458,5.101311,1.514834,0.151883,4.691983,1.731891,160.160487,160.893724,8.596799,3.520111,2.774852,4.712189,0.941412,1.389973
min,1.000000,1.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000,32.000000,0.000000,56.000000,19.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,225.000000,156.000000,4.000000,0.000000,0.000000,5.000000,0.000000,0.000000
25%,32.750000,16.750000,0.000000,35.000000,0.000000,0.000000,0.000000,7.750000,2.000000,3.000000,4.000000,3.000000,8.000000,2.000000,3.000000,3.000000,8.000000,72.750000,7.000000,149.500000,87.750000,10.000000,5.000000,1.000000,0.000000,9.000000,1.000000,398.250000,323.250000,13.000000,3.000000,2.000000,11.000000,0.000000,0.000000
50%,64.500000,32.500000,1.000000,45.000000,1.000000,0.000000,1.000000,10.000000,4.000000,4.000000,6.000000,4.000000,12.000000,4.500000,4.000000,4.000000,11.000000,93.000000,9.000000,170.500000,106.000000,15.000000,8.000000,2.000000,0.000000,12.000000,2.000000,495.500000,419.000000,19.000000,4.000000,4.000000,14.000000,0.000000,1.000000
75%,96.250000,48.250000,2.000000,51.000000,2.000000,0.000000,1.000000,14.000000,6.000000,6.000000,9.000000,5.000000,18.000000,7.000000,6.250000,6.000000,16.250000,111.250000,14.000000,188.000000,129.000000,20.000000,11.000000,2.000000,0.000000,15.000000,3.000000,589.500000,519.750000,24.000000,6.000000,6.000000,17.000000,0.000000,3.000000
max,128.000000,64.000000,7.000000,78.000000,7.000000,1.000000,6.000000,32.000000,13.000000,17.000000,24.000000,15.000000,36.000000,13.000000,16.000000,19.000000,29.000000,186.000000,192.000000,259.000000,192.000000,40.000000,27.000000,8.000000,1.000000,30.000000,10.000000,1070.000000,994.000000,53.000000,25.000000,14.000000,30.000000,5.000000,3.000000

In [4]:
df.shape

(128, 38)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [6]:
# code here
teem =df['Team'].unique().tolist() + df['Against'].unique().tolist()
teem = sorted(list(set(teem)))
team_per = {}
for i in teem:
  football_teem = df[(df['Team']==i) | (df['Against']==i)]
  Total_Attempts = football_teem['Total Attempts'].sum()
  On_Target = football_teem['On Target'].sum()

  percentage_attemt = (On_Target/Total_Attempts)*100 if Total_Attempts != 0 else 0
  team_per[i] = round(percentage_attemt,2)

team_per = dict(sorted(team_per.items(),key=lambda item:item[1],reverse=True))

team_per

{'Argentina': 42.86,
 'Serbia': 42.68,
 'Switzerland': 41.56,
 'Cameroon': 41.43,
 'Brazil': 41.13,
 'Ecuador': 40.82,
 'Ghana': 40.58,
 'England': 38.46,
 'Qatar': 38.0,
 'Iran': 37.14,
 'Croatia': 37.04,
 'Netherlands': 37.04,
 'Germany': 36.96,
 'Portugal': 36.94,
 'Saudi Arabia': 36.84,
 'Costa Rica': 36.49,
 'Spain': 36.49,
 'Poland': 35.92,
 'United States': 35.9,
 'France': 35.54,
 'Korea Republic': 35.05,
 'Canada': 33.33,
 'Senegal': 32.95,
 'Tunisia': 32.2,
 'Australia': 31.82,
 'Mexico': 31.34,
 'Wales': 30.88,
 'Japan': 30.1,
 'Belgium': 29.87,
 'Uruguay': 29.51,
 'Denmark': 28.57,
 'Morocco': 25.19,
 'Fram': 7.69}

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [7]:
# code here
df['Team'].shape[0]
matches_played = pd.DataFrame()
matches_played['Matches_Played'] = (df['Team'].value_counts() + df['Against'].value_counts()).sort_values()
matches_played.reset_index(inplace=True)
matches_played.columns=['Team','Matches_Played']
matches_played['Rank'] = matches_played['Matches_Played'].rank(method='first',ascending=False)
matches_played.fillna(matches_played.mean(),inplace=True)
matches_played['Rank'] = matches_played['Rank'].astype(int)

matches_played.sort_values(by='Rank',inplace=True)
matches_played

<ipython-input-7-d9aecfd85904>:8: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  matches_played.fillna(matches_played.mean(),inplace=True)

              Team  Matches_Played  Rank
29         Morocco        14.00000     1
30         Croatia        14.00000     2
31       Argentina        14.00000     3
28          France        13.00000     4
24        Portugal        10.00000     5
25     Netherlands        10.00000     6
26         England        10.00000     7
27          Brazil        10.00000     8
16     Switzerland         8.00000     9
17           Spain         8.00000    10
18         Senegal         8.00000    11
19   United States         8.00000    12
20           Japan         8.00000    13
21  Korea Republic         8.00000    14
22       Australia         8.00000    15
23          Poland         8.00000    16
32            Fram         7.96875    16
0            Wales         6.00000    17
1           Mexico         6.00000    18
2          Uruguay         6.00000    19
3             Iran         6.00000    20
4            Ghana         6.00000    21
5          Germany         6.00000    22
6           Serbia         6.00000    23
7     Saudi Arabia         6.00000    24
8          Ecuador         6.00000    25
9       Costa Rica         6.00000    26
10          Canada         6.00000    27
11        Cameroon         6.00000    28
12         Tunisia         6.00000    29
13         Belgium         6.00000    30
14         Denmark         6.00000    31
15           Qatar         6.00000    32

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [8]:
# code here
df.isnull().sum()

Sl. No                             0
Match No.                          0
Team                               0
Against                            0
Group                              0
Goal                               0
Possession (%)                     0
Inside Penalty Area                0
Outside Penalty Area               0
Assists                            0
Total Attempts                     0
On Target                          0
Off Target                         0
Target in Penalty                  0
Target from Outside                0
Left Channel                       0
Left Inside Channel                0
Central Channel                    0
Right Inside Channel               0
Right Channel                      0
Receptions MD                      0
Receptions D                       0
Attempted Line Breaks              0
Completed Line Breaks              0
Attempted Defensive Line Breaks    0
Completed Defensive Line Breaks    0
Yellow Cards                       0
Red Cards                          0
Fouls Against                      0
Offsides                           0
Passes                             0
Passes Completed                   0
Crosses                            0
Crosses Completed                  0
Corners                            0
Free Kicks                         0
Penalties Scored                   0
Pts                                0
dtype: int64

In [9]:
df.describe()

,Sl. No,Match No.,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,64.500000,32.500000,1.343750,43.476562,1.203125,0.117188,0.914062,11.257812,4.007812,4.835938,6.914062,4.343750,13.562500,4.671875,4.906250,4.648438,12.234375,92.703125,12.453125,169.281250,109.476562,14.812500,8.265625,1.726562,0.023438,12.320312,1.976562,502.859375,430.929688,19.523438,4.898438,4.468750,14.250000,0.335938,1.429688
std,37.094474,18.545539,1.342448,11.442403,1.324270,0.322907,1.150333,5.406683,2.588576,2.610630,3.998085,2.733397,6.901729,2.886595,3.080131,2.936573,6.176517,29.440547,18.152399,34.120661,30.776298,7.230458,5.101311,1.514834,0.151883,4.691983,1.731891,160.160487,160.893724,8.596799,3.520111,2.774852,4.712189,0.941412,1.389973
min,1.000000,1.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000,32.000000,0.000000,56.000000,19.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,225.000000,156.000000,4.000000,0.000000,0.000000,5.000000,0.000000,0.000000
25%,32.750000,16.750000,0.000000,35.000000,0.000000,0.000000,0.000000,7.750000,2.000000,3.000000,4.000000,3.000000,8.000000,2.000000,3.000000,3.000000,8.000000,72.750000,7.000000,149.500000,87.750000,10.000000,5.000000,1.000000,0.000000,9.000000,1.000000,398.250000,323.250000,13.000000,3.000000,2.000000,11.000000,0.000000,0.000000
50%,64.500000,32.500000,1.000000,45.000000,1.000000,0.000000,1.000000,10.000000,4.000000,4.000000,6.000000,4.000000,12.000000,4.500000,4.000000,4.000000,11.000000,93.000000,9.000000,170.500000,106.000000,15.000000,8.000000,2.000000,0.000000,12.000000,2.000000,495.500000,419.000000,19.000000,4.000000,4.000000,14.000000,0.000000,1.000000
75%,96.250000,48.250000,2.000000,51.000000,2.000000,0.000000,1.000000,14.000000,6.000000,6.000000,9.000000,5.000000,18.000000,7.000000,6.250000,6.000000,16.250000,111.250000,14.000000,188.000000,129.000000,20.000000,11.000000,2.000000,0.000000,15.000000,3.000000,589.500000,519.750000,24.000000,6.000000,6.000000,17.000000,0.000000,3.000000
max,128.000000,64.000000,7.000000,78.000000,7.000000,1.000000,6.000000,32.000000,13.000000,17.000000,24.000000,15.000000,36.000000,13.000000,16.000000,19.000000,29.000000,186.000000,192.000000,259.000000,192.000000,40.000000,27.000000,8.000000,1.000000,30.000000,10.000000,1070.000000,994.000000,53.000000,25.000000,14.000000,30.000000,5.000000,3.000000

In [10]:
df.dropna()
df.isnull().sum()
df

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,13,1,6,8,5,10,4,6,6,19,74,15,141,95,18,11,1,0,11,3,583,518,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,14,4,8,7,7,20,8,3,2,7,106,15,164,114,23,12,0,0,13,2,491,430,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,7,2,5,5,2,13,1,3,7,16,75,10,150,97,14,8,2,0,11,2,494,428,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,21,9,9,13,8,13,6,8,9,9,163,28,249,172,40,24,4,0,26,4,648,544,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,10,5,3,7,3,15,7,5,4,12,69,9,179,107,14,9,3,0,19,4,516,419,24,3,5,28,4,0

In [11]:
df.duplicated().sum()

0

In [12]:
df.shape

(128, 38)

In [13]:
df.drop(columns=['Match No.','Red Cards','Pts'],inplace=True)

In [14]:
df.shape

(128, 35)

###`Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [15]:
# code here
df['Rank'] = df['Team'].rank(ascending=False)
df['Rank'] = df['Rank'].astype(np.int16)
df.set_index('Rank',inplace=True)
df.sort_index(inplace=True)
df.head(3)

,Sl. No,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
Rank,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,33,Wales,Iran,B,0,51,0,0,0,10,3,4,5,5,18,3,8,11,13,101,13,208,129,17,8,1,9,2,508,413,20,5,2,12,0
2,69,Wales,England,B,0,33,0,0,0,7,1,3,1,6,7,1,2,0,4,46,1,104,55,4,1,2,16,1,325,261,4,1,1,10,0
2,8,Wales,United States,B,1,39,1,0,0,7,3,3,5,2,7,2,5,2,7,73,9,174,103,17,8,2,10,1,409,321,15,6,3,15,1

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [19]:
# code here
df1 = pd.read_csv('/content/drive/MyDrive/Compasx/Data Science Mentorship Program/dataset/dataset-session-18/train - train.csv')
df2 = pd.read_csv('/content/drive/MyDrive/Compasx/Data Science Mentorship Program/dataset/dataset-session-18/test - test.csv')

In [20]:
df1['Age'].isnull().sum()
df1.dropna(subset='Age',inplace=True)
df1['Age'].isnull().sum()

0

In [21]:
df2['Age'].isnull().sum()
df2['Age'].fillna(20,inplace=True)
df2['Age'].isnull().sum()

0

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Questions on IPL wala dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

In [ ]:
# matches_dataset = 'https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link'

In [23]:
ipl = pd.read_csv('/content/drive/MyDrive/Compasx/Data Science Mentorship Program/dataset/dataset-session-18/IPL_Matches_2008_2022.csv')

###`Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [41]:
# code here
rename = {
    'Delhi Daredevils':'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings',
    'Rising Pune Supergiants': 'Rising Pune Supergiant'
}
ipl['Team1'] = ipl['Team1'].replace(rename)
ipl['Team2'] = ipl['Team2'].replace(rename)
ipl['TossWinner'] = ipl['TossWinner'].replace(rename)
ipl['WinningTeam'] = ipl['WinningTeam'].replace(rename)

###`Q-7:` Venues with most "no result" matches.

In [42]:
# code here
ipl['NoResults'] = ipl['WonBy']=='NoResults'

In [43]:
ipl['Venue'][ipl['NoResults']==True].value_counts()

M Chinnaswamy Stadium    2
M.Chinnaswamy Stadium    1
Feroz Shah Kotla         1
Name: Venue, dtype: int64

###`Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

In [75]:
# code here
Team1Players = ipl[ipl['MatchNumber'] == 'Final']['Team1Players']
Team2Players = ipl[ipl['MatchNumber'] == 'Final']['Team2Players']
all_player = pd.Series(Team1Players+Team2Players)
player = all_player.apply(lambda x: x.split(',')).explode()
player = player.str.strip()
player_count = player.value_counts()
most_final = player_count.sort_values(ascending=False).index[0]
print(f"Player with the most appearances in the final : {most_final}")

Player with the most appearances in the final : 'MS Dhoni'

In [60]:
# Extract all players from Team1 and Team2 columns
players = pd.concat([ipl[ipl['MatchNumber'] == 'Final']['Team1Players'], ipl[ipl['MatchNumber'] == 'Final']['Team2Players']])

# Split the string into a list of players
players = players.apply(lambda x: x.split(",")).explode()

# Strip any leading and trailing whitespace from each player name
players = players.str.strip()

# Create a Series of all players and count their occurrences
player_counts = players.value_counts()

# Get the player with the most appearances in the final
most_final_appearances_player = player_counts.sort_values(ascending=False).index[0]

# Print the player with the most appearances in the final
print(f"Player with the most appearances in the final: {most_final_appearances_player}")

Player with the most appearances in the final: 'MS Dhoni'

###`Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;
For loosing - 0 Point
For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

In [78]:
# code here

###`Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.

Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [ ]:
# code here